[package]
name = "apexsky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "apexsky"
crate-type = ["staticlib"]

[dependencies]
libc = "0.2.150"
lazy_static = "1.4"
config = { version = "0.13", default-features = false, features = ["toml", "yaml"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8.8"
