[package]
name = "apexsky_dma"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
apexsky = { path = "../apexsky" }
bevy = { version = "0.13.1", features = ["wayland"] }
bevy_egui = "0.26.0"
bitset = "0.1.2"
bitset-core = "0.1.1"
chrono = "0.4.35"
#console-subscriber = "0.1.5"
dataview = "1.0.1"
rand = "0.8.5"
include-flate = "0.3.0"
indexmap = { version = "2.2.5", features = ["serde"] }
intptr = { version = "0.1.6", features = ["dataview_1", "serde"] }
memflow = "0.2.1"
memprocfs = "5.9.5"
named_constants = "0.2.0"
ndarray = "0.15.6"
obfstr = "0.4.3"
once_cell = "1.19.0"
parking_lot = { version = "0.12.1", features = ["arc_lock", "nightly", "owning_ref", "serde"] }
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["json", "chrono", "env-filter"] }
tracing-appender = "0.2.3"
