[package]
name = "apexsky_proto"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.13.2"
serde = { version = "1.0", features = ["derive"] }
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.12.3"
